#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt clobber

unsetopt correct_all
# Customize to your needs...
alias vi="nvim"
PATH="$HOME"/.local/bin:"$PATH"
source ~/.zprezto/key-bindings.zsh
