#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt clobber

unsetopt correct_all
# Customize to your needs...
eval "$(/opt/homebrew/bin/brew shellenv)"
alias vi="nvim"
PATH="/usr/local/go/bin:$HOME/go/bin:$PATH"